---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - alluxios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - alluxios/finalizers
  verbs:
  - update
- apiGroups:
  - stack.zncdata.net
  resources:
  - alluxios/status
  verbs:
  - get
  - patch
  - update
