apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: alluxio-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AlluxioClusterCluster is the Schema for the alluxioclusters API
      displayName: Alluxio Cluster
      kind: AlluxioCluster
      name: alluxioclusters.alluxio.zncdata.dev
      version: v1alpha1
  description: alluxio for operator
  displayName: alluxio-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - alluxio
  - k8s
  links:
  - name: AlluxioCluster Operator
    url: https://alluxio-operator.domain
  maturity: alpha
  provider:
    name: zncdatadev
    url: https://github.com/zncdatadev
  version: 0.0.0
